In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [4]:
l=[10,20,30,40]
arr=np.array(l)
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[10 20 30 40]
<class 'numpy.ndarray'>
1
(4,)
4
int64


In [5]:
l=[10,20,30,40.5]
arr=np.array(l)
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[10.  20.  30.  40.5]
<class 'numpy.ndarray'>
1
(4,)
4
float64


In [6]:
l=[10,20,'30',40.5]
arr=np.array(l)
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

['10' '20' '30' '40.5']
<class 'numpy.ndarray'>
1
(4,)
4
<U32


In [7]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2
(2, 3)
6
int64


In [8]:
%timeit [i**4 for i in range(1,10000)]

722 μs ± 20.4 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [2]:
%timeit np.arange(1,10000)**4

24.3 μs ± 1.38 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
