In [2]:
import numpy as np

In [3]:
arr=np.array([10,2,30,0,30,402,0,103,204,30402,3012343,3204304])
print(arr)
print(np.max(arr))
print(np.argmax(arr))

[     10       2      30       0      30     402       0     103     204
   30402 3012343 3204304]
3204304
11


In [4]:
arr=np.array([10,2,30,0,30,402,0,103,204,30402,3012343,3204304])
print(arr)
print(np.min(arr))
print(np.argmin(arr))

[     10       2      30       0      30     402       0     103     204
   30402 3012343 3204304]
0
3


In [5]:
arr=np.array([1,4,9,16,25])
print(arr)
print(np.sqrt(arr))

[ 1  4  9 16 25]
[1. 2. 3. 4. 5.]


In [8]:
arr=np.array([1,4,9,16,25])
print(arr)
print(np.cumsum(arr))  # cumullative sum

[ 1  4  9 16 25]
[ 1  5 14 30 55]


In [12]:
arr=np.array([10,20,30,40,10,302,50,30,20,0,40])
print(arr)
print(np.sort(arr))
arr1=np.sort(arr)
print(np.searchsorted(arr,9))
print(np.searchsorted(arr,[11,21,3001],side='right'))
print(np.searchsorted(arr,[11,21,3001],side='left'))

[ 10  20  30  40  10 302  50  30  20   0  40]
[  0  10  10  20  20  30  30  40  40  50 302]
0
[ 1  2 11]
[ 1  2 11]


In [14]:
arr=np.array([[10,1,98,56],[12,34,23,78]])
print(arr)
print(np.max(arr))
print(np.argmax(arr))
print(np.max(arr,axis=0))
print(np.argmax(arr,axis=0))
print(np.max(arr,axis=1))
print(np.argmax(arr,axis=1))

[[10  1 98 56]
 [12 34 23 78]]
98
2
[12 34 98 78]
[1 1 0 1]
[98 78]
[2 3]


In [15]:
arr=np.array([[10,1,98,56],[12,34,23,78]])
print(arr)
print(np.min(arr))
print(np.argmin(arr))
print(np.min(arr,axis=0))
print(np.argmin(arr,axis=0))
print(np.min(arr,axis=1))
print(np.argmin(arr,axis=1))

[[10  1 98 56]
 [12 34 23 78]]
1
1
[10  1 23 56]
[0 0 1 0]
[ 1 12]
[1 0]


In [22]:
arr=np.array([[10,1,98,56],[12,34,23,78]])
print(arr)
print(np.sqrt(arr))
print(np.cumsum(arr,axis=0))
print(np.cumsum(arr,axis=1))

[[10  1 98 56]
 [12 34 23 78]]
[[3.16227766 1.         9.89949494 7.48331477]
 [3.46410162 5.83095189 4.79583152 8.83176087]]
[[ 10   1  98  56]
 [ 22  35 121 134]]
[[ 10  11 109 165]
 [ 12  46  69 147]]


In [23]:
arr=np.array([[10,1,98,56],[12,34,23,78]])
print(arr)
print(np.sort(arr))
print(np.sort(arr,axis=0))
print(np.sort(arr,axis=1))

[[10  1 98 56]
 [12 34 23 78]]
[[ 1 10 56 98]
 [12 23 34 78]]
[[10  1 23 56]
 [12 34 98 78]]
[[ 1 10 56 98]
 [12 23 34 78]]


In [33]:
arr=(np.arange(1,28)*2).reshape(3,3,3)
print(arr)
print(np.sort(arr))


[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[20 22 24]
  [26 28 30]
  [32 34 36]]

 [[38 40 42]
  [44 46 48]
  [50 52 54]]]
[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[20 22 24]
  [26 28 30]
  [32 34 36]]

 [[38 40 42]
  [44 46 48]
  [50 52 54]]]


In [5]:
# max, min, sort
arr=np.array([10,1,78,98,17])
max_value=arr[0]
min_value=arr[0]
for i in np.nditer(arr):
    if i>max_value:
        max_value=i
for i in range(len(arr)):
    if arr[i]>max_value:
        max_value=arr[i]
for i in range(len(arr)):
    if arr[i]<min_value:
        min_value=arr[i]
for i in range(len(arr)):
    for j in range(i+1,len(arr)):
        if arr[i]>arr[j]:
            arr[i],arr[j]=arr[j],arr[i]
print(arr)
print(max_value)
print(min_value)

[ 1 10 17 78 98]
78
1
