# Broadcasting

In [1]:
import numpy as np

In [3]:
arr1=np.array([10,20,30])
arr2=np.array([10,20,30])
arr=arr1+arr2
print(arr)

[20 40 60]


In [6]:
arr1=np.array([10,20,30])
arr=arr1+4
print(arr)

[14 24 34]


In [7]:
arr1=np.array([10,20,30,40])
arr1=np.array([[1],[2],[3],[4]])
arr=arr1+arr2
print(arr)

[[11 21 31]
 [12 22 32]
 [13 23 33]
 [14 24 34]]


In [10]:
arr1=np.array([10,20,30,40])
arr2=np.array([10,20,30])
arr=arr1+arr2
print(arr)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [13]:
arr1=np.array([[10,20,30],[40,50,60]])
arr2=np.array([10,10,10])
arr=arr1+arr2
print(arr)

[[20 30 40]
 [50 60 70]]


In [15]:
arr1=np.array([[1,2],[3,4],[5,6]])
arr2=np.array([2,2,2])
arr=arr1+arr2
print(arr)

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [47]:
# create one random array having 20 integers value
arr=np.random.randint(1,20,20)
print(arr)

[ 5  9  9  8  6 15  1  3 14  7 19 17 15  3 10  3  7  9 11  8]


In [31]:
# create one linear spaced array having 10 values and the space between the elements
# is 5
arr=np.linspace(5,50,10)
print(arr)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [45]:
# create one array with the help of arange function having 12 values and reshape them
# into 2 and 3 dimension with all possible outcomes
arr=np.arange(1,13)
arr=np.arange(1,13).reshape(3,4)
arr=np.arange(1,13).reshape(4,3)
arr=np.arange(1,13).reshape(3,4,1)
arr=np.arange(1,13).reshape(4,3,1)
print(arr)

[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]
