In [2]:
import numpy as np

In [3]:
arr1=np.array([10,20,30,40])
arr2=np.array([1,2,3,4])
print(arr1)
print()
print(arr2)
arr=np.concatenate((arr1,arr2))
print(arr)

[10 20 30 40]

[1 2 3 4]
[10 20 30 40  1  2  3  4]


In [6]:
arr1=np.array([10,20,30,40])
arr2=np.array([1,2,3,4])
print(arr1)
print()
print(arr2)
arr=np.concatenate((arr1,arr2),axis=0)
print(arr)
arn=np.concatenate((arr1,arr2),axis=1)
print(arn)

[10 20 30 40]

[1 2 3 4]
[10 20 30 40  1  2  3  4]


AxisError: axis 1 is out of bounds for array of dimension 1

In [8]:
arr1=np.array([[10,20,30],[40,50,60]])
arr2=np.array([[1,2,3],[4,5,6]])
print(arr1)
print()
print(arr2)
arr=np.concatenate((arr1,arr2),axis=0)
print(arr)
arn=np.concatenate((arr1,arr2),axis=1)
print(arn)

[[10 20 30]
 [40 50 60]]

[[1 2 3]
 [4 5 6]]
[[10 20 30]
 [40 50 60]
 [ 1  2  3]
 [ 4  5  6]]
[[10 20 30  1  2  3]
 [40 50 60  4  5  6]]


In [13]:
arr1=np.arange(1,9).reshape(2,2,2)
arr2=np.arange(1,9).reshape(2,2,2)
arr=np.concatenate((arr1,arr2),axis=0)
print(arr)
arn=np.concatenate((arr1,arr2),axis=1)
print(arn)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]

 [[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 2]
  [3 4]
  [1 2]
  [3 4]]

 [[5 6]
  [7 8]
  [5 6]
  [7 8]]]


In [3]:
arr1=np.array([10,20,30,10])
arr2=np.array([1,2,3,4])
print(arr1)
print()
print(arr2)
print()
arr=np.stack((arr1,arr2))
print(arr)
arr=np.stack((arr1,arr2),axis=0)
print(arr)
arn=np.stack((arr1,arr2),axis=1)
print(arn)

[10 20 30 10]

[1 2 3 4]

[[10 20 30 10]
 [ 1  2  3  4]]
[[10 20 30 10]
 [ 1  2  3  4]]
[[10  1]
 [20  2]
 [30  3]
 [10  4]]


In [17]:
arr1=np.array([[10,20,30],[40,50,60]])
arr2=np.array([[1,2,3],[4,5,6]])
print(arr1)
print()
print(arr2)
arr=np.stack((arr1,arr2),axis=0)
print(arr)
arn=np.stack((arr1,arr2),axis=1)
print(arn)

[[10 20 30]
 [40 50 60]]

[[1 2 3]
 [4 5 6]]
[[[10 20 30]
  [40 50 60]]

 [[ 1  2  3]
  [ 4  5  6]]]
[[[10 20 30]
  [ 1  2  3]]

 [[40 50 60]
  [ 4  5  6]]]


In [18]:
arr1=np.arange(1,9).reshape(2,2,2)
arr2=np.arange(1,9).reshape(2,2,2)
arr=np.stack((arr1,arr2),axis=0)
print(arr)
arn=np.stack((arr1,arr2),axis=1)
print(arn)

[[[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]


 [[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]]
[[[[1 2]
   [3 4]]

  [[1 2]
   [3 4]]]


 [[[5 6]
   [7 8]]

  [[5 6]
   [7 8]]]]


In [19]:
arr1=np.array([10,20,30,10])
arr2=np.array([1,2,3,4])
print(arr1)
print()
print(arr2)
print()
arr=np.vstack((arr1,arr2))

[10 20 30 10]

[1 2 3 4]



In [23]:
arr1=np.array([[10,20,30],[40,50,60]])
arr2=np.array([[1,2,3],[4,5,6]])
print(arr1)
print()
print(arr2)
print()
arr=np.vstack((arr1,arr2))
print(arr)

[[10 20 30]
 [40 50 60]]

[[1 2 3]
 [4 5 6]]

[[10 20 30]
 [40 50 60]
 [ 1  2  3]
 [ 4  5  6]]


In [20]:
arr1=np.array([10,20,30,10])
arr2=np.array([1,2,3,4])
print(arr1)
print()
print(arr2)
print()
arr=np.hstack((arr1,arr2))

[10 20 30 10]

[1 2 3 4]



In [24]:
arr1=np.array([[10,20,30],[40,50,60]])
arr2=np.array([[1,2,3],[4,5,6]])
print(arr1)
print()
print(arr2)
print()
arr=np.hstack((arr1,arr2))
print(arr)

[[10 20 30]
 [40 50 60]]

[[1 2 3]
 [4 5 6]]

[[10 20 30  1  2  3]
 [40 50 60  4  5  6]]


In [5]:
arr1=np.array([10,20,30,10])
arr2=np.array([1,2,3,4])
print(arr1)
print()
print(arr2)
print()
arr=np.dstack((arr1,arr2))
print(arr)

[10 20 30 10]

[1 2 3 4]

[[[10  1]
  [20  2]
  [30  3]
  [10  4]]]


In [25]:
arr1=np.array([[10,20,30],[40,50,60]])
arr2=np.array([[1,2,3],[4,5,6]])
print(arr1)
print()
print(arr2)
print()
arr=np.dstack((arr1,arr2))
print(arr)

[[10 20 30]
 [40 50 60]]

[[1 2 3]
 [4 5 6]]

[[[10  1]
  [20  2]
  [30  3]]

 [[40  4]
  [50  5]
  [60  6]]]


In [29]:
arr=np.arange(1,10)
arr1=np.split(arr,3)
print(arr1)
for i in arr1:
    print(i)
arr2=np.split(arr,4)
print(arr2)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
[1 2 3]
[4 5 6]
[7 8 9]


ValueError: array split does not result in an equal division

In [27]:
arr=np.arange(1,10)
arr1=np.array_split(arr,4)
print(arr1)
for i in arr1:
    print(i)

[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]
