In [1]:
import numpy as np

In [2]:
# datatype
arr=np.array([10,20,30,40,50],dtype='str')
print(arr)
print(arr.dtype)

['10' '20' '30' '40' '50']
<U2


In [3]:
arr=np.array([10.0,20.0,30.0,40.0])
print(arr)
print(arr.dtype)

[10. 20. 30. 40.]
float64


In [4]:
arr1=arr.astype('int')
print(arr1)

[10 20 30 40]


In [7]:
arr1=arr.astype(int)
print(arr1)

[10 20 30 40]


In [9]:
# copy vs view
arr=np.array([10,20,30,40,50])
print(arr)
c=arr.copy()
c[2]=100
print(c)
print(arr)

[10 20 30 40 50]
[ 10  20 100  40  50]
[10 20 30 40 50]


In [11]:
arr=np.array([10,20,30,40,50])
print(arr)
v=arr.view()
v[2]=100
print(v)
print(arr)

[10 20 30 40 50]
[ 10  20 100  40  50]
[ 10  20 100  40  50]


In [12]:
arr=np.arange(1,10).reshape(3,3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
arr=np.arange(1,10)
print(arr)
print(arr[::-1])
print(arr[2::2])

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
[3 5 7 9]


In [18]:
arr=np.arange(1,10).reshape(3,3)
print(arr)
print()
print(arr[::-1])
print(arr[0][::-1])
print(arr[::-1][0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[7 8 9]
 [4 5 6]
 [1 2 3]]
[3 2 1]
[7 8 9]


In [21]:
arr=np.arange(1,28).reshape(3,3,3)
print(arr)
print()
print(arr[::-1])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

[[[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]]


In [22]:
# arithmetic
arr=np.array([10,20,30,40])
print(arr)
arr1=arr+8
print(arr1)
arr2=np.add(arr1,8)
print(arr2)

[10 20 30 40]
[18 28 38 48]
[26 36 46 56]


In [24]:
arr=np.array([10,20,30,40])
print(arr)
arr_new=arr-8
print(arr_new)
arr_new1=np.subtract(arr_new,2)
print(arr_new1)

[10 20 30 40]
[ 2 12 22 32]
[ 0 10 20 30]


In [26]:
# Reciprocal
# Reciprocal works as a floor division
arr=np.array([10,20,30,40])
print(arr)
arr1=1/arr
print(arr1)
arr2=np.reciprocal(arr)
print(arr2)

[10 20 30 40]
[0.1        0.05       0.03333333 0.025     ]
[0 0 0 0]


In [28]:
arr=np.array([10,20,30,40])
print(arr)
arr1=arr**2
print(arr1)
arr2=np.power(arr,2)
print(arr2)

[10 20 30 40]
[ 100  400  900 1600]
[ 100  400  900 1600]


In [29]:
arr=np.array([10,20,30,40])
print(arr)
arr1=arr%2
print(arr1)
arr2=np.remainder(arr,2)
print(arr2)

[10 20 30 40]
[0 0 0 0]
[0 0 0 0]
