In [1]:
import numpy as np

In [7]:
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.dtype)
print(arr.shape)
print(arr.size)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1
int64
(5,)
5


In [8]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
2
(2, 4)
8
int64


In [10]:
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
<class 'numpy.ndarray'>
3
(3, 3, 3)
27
int64


In [14]:
# arange(start,stop,step)
# it always return single dimension array
arr=np.arange(10)
print(arr)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[0 1 2 3 4 5 6 7 8 9]
(10,)
10
int64


In [24]:
arr=np.arange(1,13)
print(arr)
arr1=arr.reshape(4,3)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [27]:
arr=np.arange(1,28).reshape(3,1,9)
print(arr)

[[[ 1  2  3  4  5  6  7  8  9]]

 [[10 11 12 13 14 15 16 17 18]]

 [[19 20 21 22 23 24 25 26 27]]]


In [29]:
# indexing
arr=np.arange(1,9)
print(arr)
print(arr[-1])

[1 2 3 4 5 6 7 8]
8


In [32]:
arr=np.arange(1,9).reshape(2,4)
print(arr)
print(arr[0][-1])

[[1 2 3 4]
 [5 6 7 8]]
4


In [36]:
arr=np.arange(1,28).reshape(3,3,3)
print(arr)
print(arr[1][2][2])
print(arr[1][2][1])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
18
17


In [39]:
# iteration
arr=np.array([10,20,30,40,50])
print(arr)
for i in arr:
    print(i)

[10 20 30 40 50]
10
20
30
40
50


In [41]:
arr=np.array([10,20,30,40,50])
print(arr)
for i in range(len(arr)):
    print(i,arr[i])

[10 20 30 40 50]
0 10
1 20
2 30
3 40
4 50


In [44]:
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr)
for i in arr:
    for j in i:
        print(j)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
10
20
30
40
50
60
70
80
90


In [48]:
arr=np.arange(1,19).reshape(2,3,3)
print(arr)
for i in arr:
    for j in i:
        for k in j:
            print(k,end=" ")

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 

In [50]:
arr=np.arange(1,19).reshape(2,3,3)
print(arr)
for i in np.nditer(arr):
    print(i,end=" ")

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 

In [52]:
arr=np.arange(1,19).reshape(2,3,3)
print(arr)
for i,j in np.ndenumerate(arr):
    print(i,j)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(0, 2, 0) 7
(0, 2, 1) 8
(0, 2, 2) 9
(1, 0, 0) 10
(1, 0, 1) 11
(1, 0, 2) 12
(1, 1, 0) 13
(1, 1, 1) 14
(1, 1, 2) 15
(1, 2, 0) 16
(1, 2, 1) 17
(1, 2, 2) 18


In [1]:
# special filled array
# zeros 
import numpy as np
arr=np.zeros(4)
print(arr)

[0. 0. 0. 0.]


In [2]:
arr=np.zeros((4,2))
print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [3]:
arr=np.zeros((4,2,4))
print(arr)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [4]:
# ones
arr=np.ones(4)
print(arr)

[1. 1. 1. 1.]


In [5]:
arr=np.ones((2,4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
arr=np.ones((2,4,4))
print(arr)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [7]:
# eye 
arr=np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
arr=np.eye(3,4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [10]:
arr=np.eye(4)
print(arr)
print(arr[::-1])

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]


In [12]:
# evenly spaced array
# linspace(start,end,stop)
# both start and stop are inclusive
arr=np.linspace(0,10,4)
print(arr)

[ 0.          3.33333333  6.66666667 10.        ]


In [15]:
# random rand function
# range is between 0 and 1
# 0 is inclusive but 1 is not inclusve
arr=np.random.rand(8)
print(arr)

[0.05600088 0.96053379 0.46281265 0.20102962 0.401293   0.69002608
 0.12258214 0.15250599]


In [16]:
# random rand function
# range is between - infinity to + infinity
# it returns the value nearest to zeros
# and the mean is always zero and standard deviation is always 1
# it always follows gaussian theorem
arr=np.random.rand(8)
print(arr)

[0.03121594 0.91366018 0.37940379 0.34963928 0.83175135 0.24121786
 0.31443213 0.82779958]


In [17]:
arr=np.random.randint(20,40,(100))
print(arr)

[32 33 27 32 32 34 26 37 37 33 36 23 24 39 29 22 38 22 32 30 32 37 31 39
 29 27 36 37 34 32 22 30 36 27 39 23 31 38 37 22 37 31 29 31 29 26 31 37
 26 25 37 20 34 25 37 21 36 25 25 26 33 22 28 36 35 35 21 21 31 36 39 28
 34 24 28 24 29 32 37 30 20 34 27 28 21 36 22 23 22 23 25 37 29 31 35 38
 39 38 38 33]
